
### GET 
GET  http://localhost:8080/api/v2/product HTTP/1.1




### Get with Token
GET http://localhost:8080/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDI0MDAzMDUsImlkIjo4LCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYXJ0MTEifQ.XSD_Rx2kP8aSUz3HVONlJndlB7kBAk64Iz8zOnlJkl0
### GET ByID
GET  http://localhost:8080/api/v2/product/222 HTTP/1.1
### GET with keyword
GET  http://localhost:8080/api/v2/product?keyword=Edit HTTP/1.1




### Create
POST   http://localhost:8081/api/v2/product HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDI0MDAzMDUsImlkIjo4LCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYXJ0MTEifQ.XSD_Rx2kP8aSUz3HVONlJndlB7kBAk64Iz8zOnlJkl0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Arduino board5555
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

100
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

180
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Edit 
PUT http://localhost:8081/api/v2/product HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTk4OTg1OTQsImlkIjoxLCJsZXZlbCI6Im5vcm1hbCIsInVzZXJuYW1lIjoiYWRtaW4ifQ.e8ZcnQFnye_DldUnzyqfth37SVB0hp8ZEjvRCy7th4s
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="id";

5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name";

Arduino board (Edit)
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock";

101
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price";

200
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test_2nd.jpg"
Content-Type: image/png

< ./test_2nd.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--